name: peakOps-ml-environment
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12  # Updated to a modern, supported Python version
  - pip
  - pip:
      # Keep Azure/Protobuf packages pinned for specific compatibility
      - azureml-mlflow==1.38.0
      - azure-ai-ml==1.0.0
      - protobuf==3.20.3

      # Allow pip to get modern, compatible versions of these libraries
      - pyarrow
      - scikit-learn
      - pandas
      - joblib
      - matplotlib

      # Keep the GitHub packages as-is
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector