name: peakOps-ml-environment
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - azureml-mlflow>=1.38.0,<2.0.0
      - azure-ai-ml>=1.0.0,<2.0.0
      - protobuf>=3.20.0,<4.0.0
      - pyarrow>=10.0.0
      - scikit-learn>=1.0.0
      - pandas>=1.5.0
      - joblib>=1.0.0
      - matplotlib>=3.5.0

      # Keep the GitHub packages as-is
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector